version: '3.8'
services:
  mysqlDB:
    image: mysql:latest
    container_name: transactions-service
    restart: always
    environment:
      - MYSQL_DATABASE=mysqlDB
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysqlDB
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: mysqlDB
      DATABASE_USER: root
      DATABASE_PASS: root
      DATABASE_NAME: mysqlDB
volumes:
  mysql-volume:
